<?php

namespace ContainerAWLIMAZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LoginSuccessHandler' shared autowired service.
     *
     * @return \App\EventListener\LoginSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'LoginSuccessHandler.php';

        return $container->privates['App\\EventListener\\LoginSuccessHandler'] = new \App\EventListener\LoginSuccessHandler(($container->services['router'] ?? self::getRouterService($container)));
    }
}
