<?php

namespace ContainerRnBM79u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8loPTHzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8loPTHz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AppointmentController::index' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AppointmentController::index()', 'getAppointmentControllerindexService', true],
            'App\\Controller\\AppointmentController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AppointmentController::new()', 'getAppointmentControllernewService', true],
            'App\\Controller\\AppointmentController::adminIndex' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AppointmentController::adminIndex()', 'getAppointmentControlleradminIndexService', true],
            'App\\Controller\\AppointmentController::delete' => ['privates', '.service_locator.xSL6eaB.App\\Controller\\AppointmentController::delete()', 'getAppointmentControllerdeleteService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.dcfjolD.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\ProfileController::edit' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ProfileController::edit()', 'getProfileControllereditService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AppointmentController:index' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AppointmentController::index()', 'getAppointmentControllerindexService', true],
            'App\\Controller\\AppointmentController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AppointmentController::new()', 'getAppointmentControllernewService', true],
            'App\\Controller\\AppointmentController:adminIndex' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AppointmentController::adminIndex()', 'getAppointmentControlleradminIndexService', true],
            'App\\Controller\\AppointmentController:delete' => ['privates', '.service_locator.xSL6eaB.App\\Controller\\AppointmentController::delete()', 'getAppointmentControllerdeleteService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.dcfjolD.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\ProfileController:edit' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ProfileController::edit()', 'getProfileControllereditService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AppointmentController::index' => '?',
            'App\\Controller\\AppointmentController::new' => '?',
            'App\\Controller\\AppointmentController::adminIndex' => '?',
            'App\\Controller\\AppointmentController::delete' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProfileController::edit' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AppointmentController:index' => '?',
            'App\\Controller\\AppointmentController:new' => '?',
            'App\\Controller\\AppointmentController:adminIndex' => '?',
            'App\\Controller\\AppointmentController:delete' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProfileController:edit' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.8loPTHz'])) {
            return $container->privates['.service_locator.8loPTHz'];
        }

        return $container->privates['.service_locator.8loPTHz'] = $instance;
    }
}
