<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWLIMAZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWLIMAZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWLIMAZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWLIMAZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAWLIMAZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'AWLIMAZ',
    'container.build_id' => 'c6653490',
    'container.build_time' => 1770749497,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWLIMAZ');
