<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRnBM79u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRnBM79u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRnBM79u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRnBM79u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRnBM79u\App_KernelDevDebugContainer([
    'container.build_hash' => 'RnBM79u',
    'container.build_id' => '6472e4ed',
    'container.build_time' => 1770740483,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRnBM79u');
